# Generated by Django 6.0.4 on 2026-05-26 12:43

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customerprofile_order_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=store.models.default_delivery_date),
        ),
    ]
