# Generated by Django 6.0.4 on 2026-05-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customerprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
